import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>User Managment</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <nav className='nav' >
            <Link href={"/programs"} >
              <a className={styles.nav__link}>
                Programs
              </a>
            </Link>
            <Link href={"/beneficiaries"} className="nav__link">
              <a className={styles.nav__link}>
                Beneficiaries
              </a>
            </Link>
          </nav>
        </main>
      </div>
      <style jsx>
        {`
         nav{
          display: flex;
          justify-content: space-around;
          align-items: center;
          height: 5vh;
          background-color: #f5f5f5;
        }
        `}
      </style>
    </>
  )
}

export default Home
